<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Saques — Re.Source Admin</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<script src="https://unpkg.com/lucide@latest/dist/umd/lucide.js"></script><link rel="stylesheet" href="<?= app_url('/public/css/admin-dashboard.css') ?>"><link rel="stylesheet" href="<?= app_url('/public/css/admin-finance.css') ?>"><link rel="stylesheet" href="<?= asset_url('/css/flash.css') ?>"></head>
<body><header class="site-header"><?php require __DIR__.'/../../components/topbar.php'; require __DIR__.'/../../components/navbar.php'; ?></header><?php require __DIR__.'/../../components/flash.php'; ?>
<main class="finance-admin"><section class="finance-heading"><div><span>FINANCEIRO INTERNO</span><h1>Aprovação de saques</h1><p>Analise solicitações PIX/TED. Aprovações e recusas ficam registradas na auditoria.</p></div><a href="<?= app_url('/admin/saques/exportar') ?>" class="export-button"><i data-lucide="file-down"></i> Exportar CSV</a></section>
<section class="finance-metrics"><article><span>Pendentes</span><strong><?= $metrics['saques_pendentes'] ?></strong></article><article><span>Valor reservado</span><strong>R$ <?= number_format($metrics['valor_pendente'],2,',','.') ?></strong></article><article><span>Aprovado</span><strong>R$ <?= number_format($metrics['valor_aprovado'],2,',','.') ?></strong></article><article><span>Recusado</span><strong>R$ <?= number_format($metrics['valor_rejeitado'],2,',','.') ?></strong></article></section>
<section class="finance-filters"><form method="get"><input name="q" value="<?= htmlspecialchars($q,ENT_QUOTES,'UTF-8') ?>" placeholder="Empresa ou CNPJ"><select name="status"><option value="">Todos os status</option><?php foreach(['pending'=>'Pendente','completed'=>'Aprovado','rejected'=>'Rejeitado'] as $v=>$l): ?><option value="<?= $v ?>" <?= $status===$v?'selected':'' ?>><?= $l ?></option><?php endforeach ?></select><select name="method"><option value="">PIX e TED</option><option value="pix" <?= $method==='pix'?'selected':'' ?>>PIX</option><option value="ted" <?= $method==='ted'?'selected':'' ?>>TED</option></select><button>Filtrar</button></form></section>
<section class="withdrawal-list"><?php if(!$withdrawals): ?><div class="finance-empty">Nenhuma solicitação encontrada.</div><?php endif; foreach($withdrawals as $w): $name=$w['nome_fantasia']?:$w['razao_social']; ?>
<article class="withdrawal-card"><div class="withdrawal-top"><span class="finance-status <?= $w['status'] ?>"><?= ['pending'=>'Pendente','completed'=>'Aprovado','rejected'=>'Rejeitado'][$w['status']] ?></span><time><?= date('d/m/Y H:i',strtotime($w['created_at'])) ?></time></div><div class="withdrawal-main"><div><small>Empresa</small><strong><?= htmlspecialchars($name,ENT_QUOTES,'UTF-8') ?></strong><span><?= htmlspecialchars($w['cnpj'],ENT_QUOTES,'UTF-8') ?></span></div><div><small>Método</small><strong><?= strtoupper($w['method']) ?></strong><span><?= $w['method']==='pix'?htmlspecialchars(($w['pix_key_type'].' · '.$w['pix_key']),ENT_QUOTES,'UTF-8'):htmlspecialchars(($w['bank_name'].' · Ag. '.$w['agency'].' · Cc. '.$w['account_number'].'-'.$w['account_digit']),ENT_QUOTES,'UTF-8') ?></span></div><div><small>Valor</small><strong class="money">R$ <?= number_format($w['amount'],2,',','.') ?></strong><span>Titular: <?= htmlspecialchars($w['account_holder_name'],ENT_QUOTES,'UTF-8') ?></span></div></div>
<?php if($w['status']==='pending'): ?><div class="review-actions"><form method="post" action="<?= app_url('/admin/saques/aprovar') ?>" onsubmit="return confirm('Aprovar este saque manualmente?')"><?= csrf_field() ?><input type="hidden" name="withdrawal_id" value="<?= $w['id'] ?>"><input name="reason" maxlength="500" placeholder="Observação administrativa (opcional)"><button class="approve"><i data-lucide="check"></i>Aprovar</button></form><form method="post" action="<?= app_url('/admin/saques/recusar') ?>"><?= csrf_field() ?><input type="hidden" name="withdrawal_id" value="<?= $w['id'] ?>"><input name="reason" minlength="5" maxlength="500" required placeholder="Motivo da recusa"><button class="reject"><i data-lucide="x"></i>Recusar</button></form></div><?php else: ?><p class="review-result">Analisado por <?= htmlspecialchars($w['reviewer_name']??'Administrador',ENT_QUOTES,'UTF-8') ?> em <?= $w['reviewed_at']?date('d/m/Y H:i',strtotime($w['reviewed_at'])):'-' ?><?= $w['rejection_reason']?' · '.$w['rejection_reason']:'' ?></p><?php endif; ?></article><?php endforeach ?></section>
<section class="audit-section"><h2>Histórico administrativo</h2><?php if(!$auditHistory): ?><p>Nenhuma ação financeira registrada.</p><?php else: ?><div class="audit-list"><?php foreach($auditHistory as $log): ?><div><i data-lucide="shield-check"></i><span><strong><?= htmlspecialchars($log['action'],ENT_QUOTES,'UTF-8') ?></strong><?= htmlspecialchars(($log['company_name']?:'Empresa').' · '.($log['user_name']?:'Sistema'),ENT_QUOTES,'UTF-8') ?></span><time><?= date('d/m/Y H:i',strtotime($log['created_at'])) ?></time></div><?php endforeach ?></div><?php endif ?></section></main><script>lucide.createIcons()</script></body></html>
